baseurl: "https://zachsalazar.xyz"
publishDir: docs
languageCode: "en-us"
title: "Zach Salazar"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Blog
      url: "blog/"
      weight: 2
    - name: Published
      url: "published/"
      weight: 3
    - name: In Progress
      url: "inprogress/"
      weight: 4
    - name: Data
      url: "data/"
      weight: 5
    - name: Teaching
      url: "teaching/"
      weight: 6
    - name: CV
      url: "Zach_Salazar_CV.pdf"
      weight: 7
    - name: RSS
      url: "index.xml"

params:
  description: "Political Science PhD Student at the University of Illinois Urbana-Champaign."
  footer: "&copy; Zach Salazar {Year} | [Github](https://github.com/zachsalazar)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
